### ISSUE TITLE
Insufficient describing data(metadata/tags) for persistentLogs/liveLogs 

### ISSUE THREAD

**Issue by ellenreslig** [eiffel-community/eiffel#166]
To be able to search on a logs based on more than a describing name I suggest to add a field
data.liveLogs.tags  
data.perpersistentLogs.tags

The new data member "tags" type must allow specifying several tags in a "key1":"value1", "key2":"value2" fashion, or array with ["key1":"value1"]

This is needed, for example, to find all logs from a specific tool or a specific type of log. Metadata tag could then describe the producer of the log and its type.
ex.
"Producer":"Tool1234","type":"deploymentlog"

**Comment by d-stahl-ericsson** [comment]
Makes sense to me. Please feel free to submit a PR :)

**Comment by magnusbaeck** [comment]
I don't think we should allow arbitrary key/value pair since document databases where events might get stored don't necessarily handle large field cardinalities well. However, I'd be very much in favor of having a `tags` string array member with arbitrary strings (similar to `data.categories` for ActT) and ideally also a `contentType` (or `mimeType`) string member that would allow a consumer to pick the most useful representation of the same log depending on the purpose. Example:

```
"liveLogs": [
  {
    "name": "Fnord task log",
    "uri": "http://example.com/e881c480-5a38-44a1-a2c5-de6996697763",
    "tags": ["fnord"],
    "contentType": "text/html"
  },
  {
    "name": "Fnord task log",
    "uri": "http://example.com/e881c480-5a38-44a1-a2c5-de6996697763?format=plain",
    "tags": ["fnord"],
    "contentType": "text/plain"
  },
  {
    "name": "Fnord task log",
    "uri": "http://example.com/e881c480-5a38-44a1-a2c5-de6996697763?format=json",
    "tags": ["fnord"],
    "contentType": "application/json"
  }
]
```
