### ISSUE TITLE
Inconsistency in linking for TCT and CLM

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/eiffel#317]
### Description

We have an inconsistency that should either be explained or changed:

* [CLM](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelConfidenceLevelModifiedEvent.md) allows to [SUBJECT](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelConfidenceLevelModifiedEvent.md#subject) link to CD, ArtC, as well as SCC and SCS 

* [TCT](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseTriggeredEvent.md) link [Item Under Test (IUT)](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseTriggeredEvent.md#iut) only allows CD or ArtC as targets, enforcing an extra [CD](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelCompositionDefinedEvent.md) with [ELEMENT](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelCompositionDefinedEvent.md#element) link to use SCC as IUT when running tests on source code.

### Motivation

Confusing why you can set a confidence level on for example a SCS event but you can't use the same event as a IUT link

### Exemplification

You can run test on source code and then put a CLM without having to introduce a CD

### Benefits

More logical protocol

### Possible Drawbacks

None that I can think of

**Comment by magnusbaeck** [comment]
I agree. Consistency aside I think we should have good reasons for forcing extra levels of events that don't add any extra information. One could argue that it's beneficial to keep the number of event types you can link to down so that there's only one way of doing things ("what to communicate is volitional; how to communicate it is not"), but IUT can link to a couple of different types anyway, and a CD target might in turn link to other CDs so any query or other code that traverses the graph to e.g. find the underlying source change events would have to non-trivial anyway.
